const REGEXP_EMAIL = /^([^ ]+@[^ ]+\.[a-z]{2,6}|)$/;
const REGEXP_NAME = /[a-zа-я\- ]/gmi;
const SHORT_MOVIES_LENGTH = 40;
const MOVIES_PER_PAGE_SIZE_MORE_1280 = 12;
const MOVIES_PER_PAGE_SIZE_761_1279 = 8;
const MOVIES_PER_PAGE_SIZE_LESS_761 = 5;
const MOVIES_BTN_ADD_SIZE_MORE_1280 = 3;
const MOVIES_BTN_ADD_SIZE_LESS_1279 = 2;


export {
    REGEXP_EMAIL,
    REGEXP_NAME,
    SHORT_MOVIES_LENGTH,
    MOVIES_PER_PAGE_SIZE_MORE_1280,
    MOVIES_PER_PAGE_SIZE_761_1279,
    MOVIES_PER_PAGE_SIZE_LESS_761,
    MOVIES_BTN_ADD_SIZE_MORE_1280,
    MOVIES_BTN_ADD_SIZE_LESS_1279,
};